export const activitesMetadata: ActivitesMetadata[] = [
  {
    date: "01/09/2023",
    dnaIndex: 4,
    nbPlacesIndex: 7,
    desinsectisationIndex: null,
    remiseEnEtatIndex: null,
    sousOccupationIndex: null,
    travauxIndex: null,
    placesHorsDnaNgIndex: null,
    placesIndisponiblesIndex: 8,
    placesOccupeesIndex: 10,
    placesPIBPIIndex: 11,
    placesPIdebouteesIndex: 13,
  },
  {
    date: "01/10/2023",
    dnaIndex: 4,
    nbPlacesIndex: 7,
    desinsectisationIndex: null,
    remiseEnEtatIndex: null,
    sousOccupationIndex: null,
    travauxIndex: null,
    placesHorsDnaNgIndex: null,
    placesIndisponiblesIndex: 8,
    placesOccupeesIndex: 10,
    placesPIBPIIndex: 11,
    placesPIdebouteesIndex: 13,
  },
  {
    date: "01/11/2023",
    dnaIndex: 4,
    nbPlacesIndex: 7,
    desinsectisationIndex: null,
    remiseEnEtatIndex: null,
    sousOccupationIndex: null,
    travauxIndex: null,
    placesHorsDnaNgIndex: null,
    placesIndisponiblesIndex: 8,
    placesOccupeesIndex: 10,
    placesPIBPIIndex: 11,
    placesPIdebouteesIndex: 13,
  },
  {
    date: "01/12/2023",
    dnaIndex: 4,
    nbPlacesIndex: 7,
    desinsectisationIndex: null,
    remiseEnEtatIndex: null,
    sousOccupationIndex: null,
    travauxIndex: null,
    placesHorsDnaNgIndex: null,
    placesIndisponiblesIndex: 8,
    placesOccupeesIndex: null,
    tauxOccupationIndex: 9,
    placesPIBPIIndex: 11,
    placesPIdebouteesIndex: 13,
  },
  {
    date: "01/01/2024",
    dnaIndex: 4,
    nbPlacesIndex: 7,
    desinsectisationIndex: null,
    remiseEnEtatIndex: null,
    sousOccupationIndex: null,
    travauxIndex: null,
    placesHorsDnaNgIndex: null,
    placesIndisponiblesIndex: 8,
    placesOccupeesIndex: null,
    tauxOccupationIndex: 9,
    placesPIBPIIndex: 11,
    placesPIdebouteesIndex: 13,
  },
  {
    date: "01/02/2024",
    dnaIndex: 5,
    nbPlacesIndex: 8,
    desinsectisationIndex: 9,
    remiseEnEtatIndex: 10,
    sousOccupationIndex: 11,
    travauxIndex: 12,
    placesHorsDnaNgIndex: null,
    placesIndisponiblesIndex: 13,
    placesOccupeesIndex: 16,
    placesPIBPIIndex: 17,
    placesPIdebouteesIndex: 19,
  },
  {
    date: "01/03/2024",
    dnaIndex: 4,
    nbPlacesIndex: 7,
    desinsectisationIndex: 8,
    placesHorsDnaNgIndex: 9,
    remiseEnEtatIndex: 10,
    sousOccupationIndex: 11,
    travauxIndex: 12,
    placesIndisponiblesIndex: 13,
    placesOccupeesIndex: 16,
    placesPIBPIIndex: 17,
    placesPIdebouteesIndex: 19,
  },
  {
    date: "01/04/2024",
    dnaIndex: 4,
    nbPlacesIndex: 7,
    desinsectisationIndex: 8,
    placesHorsDnaNgIndex: 9,
    remiseEnEtatIndex: 10,
    sousOccupationIndex: 11,
    travauxIndex: 12,
    placesIndisponiblesIndex: 13,
    placesOccupeesIndex: 16,
    placesPIBPIIndex: 17,
    placesPIdebouteesIndex: 19,
  },
  {
    date: "01/05/2024",
    dnaIndex: 4,
    nbPlacesIndex: 7,
    desinsectisationIndex: 8,
    placesHorsDnaNgIndex: 9,
    remiseEnEtatIndex: 10,
    sousOccupationIndex: 11,
    travauxIndex: 12,
    placesIndisponiblesIndex: 13,
    placesOccupeesIndex: 16,
    placesPIBPIIndex: 18,
    placesPIdebouteesIndex: 20,
  },
  {
    date: "01/06/2024",
    dnaIndex: 4,
    nbPlacesIndex: 7,
    desinsectisationIndex: 8,
    placesHorsDnaNgIndex: 9,
    remiseEnEtatIndex: 10,
    sousOccupationIndex: 11,
    travauxIndex: 12,
    placesIndisponiblesIndex: 13,
    placesOccupeesIndex: 16,
    placesPIBPIIndex: 17,
    placesPIdebouteesIndex: 19,
  },
  {
    date: "01/07/2024",
    dnaIndex: 4,
    nbPlacesIndex: 7,
    desinsectisationIndex: 8,
    placesHorsDnaNgIndex: 9,
    remiseEnEtatIndex: 10,
    sousOccupationIndex: 11,
    travauxIndex: 12,
    placesIndisponiblesIndex: 13,
    placesOccupeesIndex: 17,
    placesPIBPIIndex: 18,
    placesPIdebouteesIndex: 20,
  },
  {
    date: "01/08/2024",
    dnaIndex: 4,
    nbPlacesIndex: 7,
    desinsectisationIndex: 8,
    remiseEnEtatIndex: 9,
    sousOccupationIndex: 10,
    travauxIndex: 11,
    placesHorsDnaNgIndex: null,
    placesIndisponiblesIndex: 12,
    placesOccupeesIndex: 15,
    placesPIBPIIndex: 16,
    placesPIdebouteesIndex: 18,
  },
  {
    date: "01/09/2024",
    dnaIndex: 4,
    nbPlacesIndex: 7,
    desinsectisationIndex: 8,
    remiseEnEtatIndex: 9,
    sousOccupationIndex: 10,
    travauxIndex: 11,
    placesHorsDnaNgIndex: null,
    placesIndisponiblesIndex: 12,
    placesOccupeesIndex: 15,
    placesPIBPIIndex: 16,
    placesPIdebouteesIndex: 18,
  },
  {
    date: "01/10/2024",
    dnaIndex: 4,
    nbPlacesIndex: 7,
    desinsectisationIndex: 8,
    remiseEnEtatIndex: 9,
    sousOccupationIndex: 10,
    travauxIndex: 11,
    placesHorsDnaNgIndex: null,
    placesIndisponiblesIndex: 12,
    placesOccupeesIndex: 15,
    placesPIBPIIndex: 16,
    placesPIdebouteesIndex: 18,
  },
  {
    date: "01/11/2024",
    dnaIndex: 4,
    nbPlacesIndex: 7,
    desinsectisationIndex: 8,
    remiseEnEtatIndex: 9,
    sousOccupationIndex: 10,
    travauxIndex: 11,
    placesHorsDnaNgIndex: null,
    placesIndisponiblesIndex: 12,
    placesOccupeesIndex: 15,
    placesPIBPIIndex: 16,
    placesPIdebouteesIndex: 18,
  },
  {
    date: "01/12/2024",
    dnaIndex: 4,
    nbPlacesIndex: 7,
    desinsectisationIndex: 8,
    remiseEnEtatIndex: 9,
    sousOccupationIndex: 10,
    travauxIndex: 11,
    placesHorsDnaNgIndex: null,
    placesIndisponiblesIndex: 12,
    placesOccupeesIndex: 15,
    placesPIBPIIndex: 16,
    placesPIdebouteesIndex: 18,
  },
  {
    date: "01/01/2025",
    dnaIndex: 4,
    nbPlacesIndex: 7,
    desinsectisationIndex: 8,
    remiseEnEtatIndex: 9,
    sousOccupationIndex: 10,
    travauxIndex: 11,
    placesHorsDnaNgIndex: null,
    placesIndisponiblesIndex: 12,
    placesOccupeesIndex: 15,
    placesPIBPIIndex: 16,
    placesPIdebouteesIndex: 18,
  },
  {
    date: "01/02/2025",
    dnaIndex: 4,
    nbPlacesIndex: 7,
    desinsectisationIndex: 8,
    remiseEnEtatIndex: 9,
    sousOccupationIndex: 10,
    travauxIndex: 11,
    placesHorsDnaNgIndex: null,
    placesIndisponiblesIndex: 12,
    placesOccupeesIndex: 15,
    placesPIBPIIndex: 16,
    placesPIdebouteesIndex: 18,
  },
];

export type ActivitesMetadata = {
  date: string;
  dnaIndex: number;
  nbPlacesIndex: number;
  desinsectisationIndex: number | null;
  remiseEnEtatIndex: number | null;
  sousOccupationIndex: number | null;
  travauxIndex: number | null;
  placesHorsDnaNgIndex: number | null;
  placesIndisponiblesIndex: number;
  placesOccupeesIndex: number | null;
  placesPIBPIIndex: number;
  placesPIdebouteesIndex: number;
  tauxOccupationIndex?: number;
};
