-- AlterTable
ALTER TABLE "Budget" ALTER COLUMN "ETP" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "tauxEncadrement" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "coutJournalier" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "dotationDemandee" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "dotationAccordee" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "totalProduits" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "totalCharges" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "cumulResultatsNetsCPOM" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "repriseEtat" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "chargesNonReconductibles" DROP NOT NULL,
ALTER COLUMN "chargesNonReconductibles" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "reserveCompensationDeficits" DROP NOT NULL,
ALTER COLUMN "reserveCompensationDeficits" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "reserveCompensationBFR" DROP NOT NULL,
ALTER COLUMN "reserveCompensationBFR" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "reserveCompensationAmortissements" DROP NOT NULL,
ALTER COLUMN "reserveCompensationAmortissements" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "fondsDedies" DROP NOT NULL,
ALTER COLUMN "fondsDedies" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "reserveInvestissement" DROP NOT NULL,
ALTER COLUMN "reserveInvestissement" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "affectationReservesFondsDedies" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "FileUpload" ADD COLUMN     "controleId" INTEGER,
ADD COLUMN     "endDate" TIMESTAMP(3),
ADD COLUMN     "startDate" TIMESTAMP(3);

-- AddForeignKey
ALTER TABLE "FileUpload" ADD CONSTRAINT "FileUpload_controleId_fkey" FOREIGN KEY ("controleId") REFERENCES "Controle"("id") ON DELETE SET NULL ON UPDATE CASCADE;
