export type Budget = {
  id: number;
  structureDnaCode: string;
  date: Date;
  ETP: number;
  tauxEncadrement: number;
  coutJournalier: number;
  dotationDemandee: number | null;
  dotationAccordee: number | null;
  totalProduits: number | null;
  totalCharges: number | null;
  totalChargesProposees: number | null;
  cumulResultatsNetsCPOM: number | null;
  repriseEtat: number | null;
  excedentRecupere: number | null;
  excedentDeduit: number | null;
  reserveInvestissement: number;
  chargesNonReconductibles: number;
  reserveCompensationDeficits: number;
  reserveCompensationBFR: number;
  reserveCompensationAmortissements: number;
  affectationReservesFondsDedies: number | null;
  autre: number | null;
  reportANouveau: number | null;
  fondsDedies: number;
  commentaire?: string;
};
