export const activitesMetadata: ActivitesMetadata[] = [
  {
    date: "01/02/2024",
    dnaIndex: 5,
    placesAutoriseesIndex: 8,
    desinsectisationIndex: 9,
    remiseEnEtatIndex: 10,
    sousOccupationIndex: 11,
    travauxIndex: 12,
    placesIndisponiblesIndex: 13,
    placesOccupeesIndex: 16,
    presencesInduesBPIIndex: 17,
    presencesInduesDebouteesIndex: 19,
  },
  {
    date: "01/03/2024",
    dnaIndex: 4,
    placesAutoriseesIndex: 7,
    desinsectisationIndex: 8,
    remiseEnEtatIndex: 10,
    sousOccupationIndex: 11,
    travauxIndex: 12,
    placesIndisponiblesIndex: 13,
    placesOccupeesIndex: 16,
    presencesInduesBPIIndex: 17,
    presencesInduesDebouteesIndex: 19,
  },
  {
    date: "01/04/2024",
    dnaIndex: 4,
    placesAutoriseesIndex: 7,
    desinsectisationIndex: 8,
    remiseEnEtatIndex: 10,
    sousOccupationIndex: 11,
    travauxIndex: 12,
    placesIndisponiblesIndex: 13,
    placesOccupeesIndex: 16,
    presencesInduesBPIIndex: 17,
    presencesInduesDebouteesIndex: 19,
  },
  {
    date: "01/05/2024",
    dnaIndex: 4,
    placesAutoriseesIndex: 7,
    desinsectisationIndex: 8,
    remiseEnEtatIndex: 10,
    sousOccupationIndex: 11,
    travauxIndex: 12,
    placesIndisponiblesIndex: 13,
    placesOccupeesIndex: 16,
    presencesInduesBPIIndex: 18,
    presencesInduesDebouteesIndex: 20,
  },
  {
    date: "01/06/2024",
    dnaIndex: 4,
    placesAutoriseesIndex: 7,
    desinsectisationIndex: 8,
    remiseEnEtatIndex: 10,
    sousOccupationIndex: 11,
    travauxIndex: 12,
    placesIndisponiblesIndex: 13,
    placesOccupeesIndex: 16,
    presencesInduesBPIIndex: 17,
    presencesInduesDebouteesIndex: 19,
  },
  {
    date: "01/07/2024",
    dnaIndex: 4,
    placesAutoriseesIndex: 7,
    desinsectisationIndex: 8,
    remiseEnEtatIndex: 10,
    sousOccupationIndex: 11,
    travauxIndex: 12,
    placesIndisponiblesIndex: 13,
    placesOccupeesIndex: 17,
    presencesInduesBPIIndex: 18,
    presencesInduesDebouteesIndex: 20,
  },
  {
    date: "01/08/2024",
    dnaIndex: 4,
    placesAutoriseesIndex: 7,
    desinsectisationIndex: 8,
    remiseEnEtatIndex: 9,
    sousOccupationIndex: 10,
    travauxIndex: 11,
    placesIndisponiblesIndex: 12,
    placesOccupeesIndex: 15,
    presencesInduesBPIIndex: 16,
    presencesInduesDebouteesIndex: 18,
  },
  {
    date: "01/09/2024",
    dnaIndex: 4,
    placesAutoriseesIndex: 7,
    desinsectisationIndex: 8,
    remiseEnEtatIndex: 9,
    sousOccupationIndex: 10,
    travauxIndex: 11,
    placesIndisponiblesIndex: 12,
    placesOccupeesIndex: 15,
    presencesInduesBPIIndex: 16,
    presencesInduesDebouteesIndex: 18,
  },
  {
    date: "01/10/2024",
    dnaIndex: 4,
    placesAutoriseesIndex: 7,
    desinsectisationIndex: 8,
    remiseEnEtatIndex: 9,
    sousOccupationIndex: 10,
    travauxIndex: 11,
    placesIndisponiblesIndex: 12,
    placesOccupeesIndex: 15,
    presencesInduesBPIIndex: 16,
    presencesInduesDebouteesIndex: 18,
  },
  {
    date: "01/11/2024",
    dnaIndex: 4,
    placesAutoriseesIndex: 7,
    desinsectisationIndex: 8,
    remiseEnEtatIndex: 9,
    sousOccupationIndex: 10,
    travauxIndex: 11,
    placesIndisponiblesIndex: 12,
    placesOccupeesIndex: 15,
    presencesInduesBPIIndex: 16,
    presencesInduesDebouteesIndex: 18,
  },
  {
    date: "01/12/2024",
    dnaIndex: 4,
    placesAutoriseesIndex: 7,
    desinsectisationIndex: 8,
    remiseEnEtatIndex: 9,
    sousOccupationIndex: 10,
    travauxIndex: 11,
    placesIndisponiblesIndex: 12,
    placesOccupeesIndex: 15,
    presencesInduesBPIIndex: 16,
    presencesInduesDebouteesIndex: 18,
  },
  {
    date: "01/01/2025",
    dnaIndex: 4,
    placesAutoriseesIndex: 7,
    desinsectisationIndex: 8,
    remiseEnEtatIndex: 9,
    sousOccupationIndex: 10,
    travauxIndex: 11,
    placesIndisponiblesIndex: 12,
    placesOccupeesIndex: 15,
    presencesInduesBPIIndex: 16,
    presencesInduesDebouteesIndex: 18,
  },
  {
    date: "01/02/2025",
    dnaIndex: 4,
    placesAutoriseesIndex: 7,
    desinsectisationIndex: 8,
    remiseEnEtatIndex: 9,
    sousOccupationIndex: 10,
    travauxIndex: 11,
    placesIndisponiblesIndex: 12,
    placesOccupeesIndex: 15,
    presencesInduesBPIIndex: 16,
    presencesInduesDebouteesIndex: 18,
  },
];

export type ActivitesMetadata = {
  date: string;
  dnaIndex: number;
  placesAutoriseesIndex: number;
  desinsectisationIndex: number | null;
  remiseEnEtatIndex: number | null;
  sousOccupationIndex: number | null;
  travauxIndex: number | null;
  placesIndisponiblesIndex: number;
  placesOccupeesIndex: number | null;
  presencesInduesBPIIndex: number;
  presencesInduesDebouteesIndex: number;
  tauxOccupationIndex?: number;
};
